    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="fonts/font-awesome.min.css">
    <link rel="stylesheet" href="fonts/ionicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Atma">
    <link rel="stylesheet" href="css/Bold-BS4-Jumbotron-with-Particles-js-1.css">
    <link rel="stylesheet" href="css/Bold-BS4-Jumbotron-with-Particles-js.css">
    <link rel="stylesheet" href="css/Card-Carousel-1.css">
    <link rel="stylesheet" href="css/Card-Carousel.css">
    <link rel="stylesheet" href="css/Customizable-Carousel-swipe-enabled.css">
    <link rel="stylesheet" href="css/Footer-Dark-1.css">
    <link rel="stylesheet" href="css/Footer-Dark.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.3.1/css/swiper.min.css">
    <link rel="stylesheet" href="css/MUSA_carousel-extended-1.css">
    <link rel="stylesheet" href="css/MUSA_carousel-extended.css">
    <link rel="stylesheet" href="css/Navigation-with-Button-1.css">
    <link rel="stylesheet" href="css/Navigation-with-Button.css">
    <link rel="stylesheet" href="css/Pretty-Product-List.css">
    <link rel="stylesheet" href="css/Responsive-Card-Item-List.css">
    <link rel="stylesheet" href="css/Simple-Slider.css">
    <link rel="stylesheet" href="css/styles.css">